name: compile-and-test
run-name: compile-and-test

on: [push]

jobs:
  compile-and-test:
    name: compile-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y build-essential
          apt-get update && apt-get install -y wget
          apt-get update && apt-get install -y gfortran
          apt-get update && apt-get install -y gnuplot
      - name: Download IRI 2016 and create run directory
        run: bash download-IRI-2016.bash
      - name: Compile
        run: make
      - name: Run the example.
        run: bash example.bash
